/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                    "text/json": components["schemas"]["RegisterRequest"];
                    "application/*+json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RegisterResponse"];
                        "application/json": components["schemas"]["RegisterResponse"];
                        "text/json": components["schemas"]["RegisterResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                    "text/json": components["schemas"]["LoginRequest"];
                    "application/*+json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuthResponse"];
                        "application/json": components["schemas"]["AuthResponse"];
                        "text/json": components["schemas"]["AuthResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RefreshRequest"];
                    "text/json": components["schemas"]["RefreshRequest"];
                    "application/*+json": components["schemas"]["RefreshRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuthResponse"];
                        "application/json": components["schemas"]["AuthResponse"];
                        "text/json": components["schemas"]["AuthResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/venues/{venueId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    venueId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["EventResponse"][];
                        "application/json": components["schemas"]["EventResponse"][];
                        "text/json": components["schemas"]["EventResponse"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    venueId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateEventRequest"];
                    "text/json": components["schemas"]["CreateEventRequest"];
                    "application/*+json": components["schemas"]["CreateEventRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["EventResponse"];
                        "application/json": components["schemas"]["EventResponse"];
                        "text/json": components["schemas"]["EventResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/venues/{venueId}/events/{eventId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    venueId: string;
                    eventId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["EventResponse"];
                        "application/json": components["schemas"]["EventResponse"];
                        "text/json": components["schemas"]["EventResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["InvitationResponse"][];
                        "application/json": components["schemas"]["InvitationResponse"][];
                        "text/json": components["schemas"]["InvitationResponse"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateInvitationRequest"];
                    "text/json": components["schemas"]["CreateInvitationRequest"];
                    "application/*+json": components["schemas"]["CreateInvitationRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["InvitationResponse"];
                        "application/json": components["schemas"]["InvitationResponse"];
                        "text/json": components["schemas"]["InvitationResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invitations/{invitationId}/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    invitationId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["InvitationResponse"];
                        "application/json": components["schemas"]["InvitationResponse"];
                        "text/json": components["schemas"]["InvitationResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invitations/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AcceptInvitationRequest"];
                    "text/json": components["schemas"]["AcceptInvitationRequest"];
                    "application/*+json": components["schemas"]["AcceptInvitationRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AcceptInvitationResponse"];
                        "application/json": components["schemas"]["AcceptInvitationResponse"];
                        "text/json": components["schemas"]["AcceptInvitationResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invitations/{invitationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    invitationId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/venues/{venueId}/events/{eventId}/ledger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    venueId: string;
                    eventId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LedgerGridResponse"];
                        "application/json": components["schemas"]["LedgerGridResponse"];
                        "text/json": components["schemas"]["LedgerGridResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/venues/{venueId}/events/{eventId}/recalculate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    venueId: string;
                    eventId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LedgerGridResponse"];
                        "application/json": components["schemas"]["LedgerGridResponse"];
                        "text/json": components["schemas"]["LedgerGridResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/venues/{venueId}/events/{eventId}/lock-budget": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    venueId: string;
                    eventId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["EventResponse"];
                        "application/json": components["schemas"]["EventResponse"];
                        "text/json": components["schemas"]["EventResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/venues/{venueId}/events/{eventId}/line-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    venueId: string;
                    eventId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateLineItemRequest"];
                    "text/json": components["schemas"]["CreateLineItemRequest"];
                    "application/*+json": components["schemas"]["CreateLineItemRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LineItemDto"];
                        "application/json": components["schemas"]["LineItemDto"];
                        "text/json": components["schemas"]["LineItemDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/venues/{venueId}/events/{eventId}/line-items/{lineItemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    venueId: string;
                    eventId: string;
                    lineItemId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateLineItemRequest"];
                    "text/json": components["schemas"]["UpdateLineItemRequest"];
                    "application/*+json": components["schemas"]["UpdateLineItemRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LineItemDto"];
                        "application/json": components["schemas"]["LineItemDto"];
                        "text/json": components["schemas"]["LineItemDto"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    venueId: string;
                    eventId: string;
                    lineItemId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/venues/{venueId}/events/{eventId}/artists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    venueId: string;
                    eventId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateArtistRequest"];
                    "text/json": components["schemas"]["CreateArtistRequest"];
                    "application/*+json": components["schemas"]["CreateArtistRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["EventArtistDto"];
                        "application/json": components["schemas"]["EventArtistDto"];
                        "text/json": components["schemas"]["EventArtistDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/venues/{venueId}/events/{eventId}/artists/{artistId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    venueId: string;
                    eventId: string;
                    artistId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateArtistRequest"];
                    "text/json": components["schemas"]["UpdateArtistRequest"];
                    "application/*+json": components["schemas"]["UpdateArtistRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["EventArtistDto"];
                        "application/json": components["schemas"]["EventArtistDto"];
                        "text/json": components["schemas"]["EventArtistDto"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    venueId: string;
                    eventId: string;
                    artistId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateOrganizationRequest"];
                    "text/json": components["schemas"]["CreateOrganizationRequest"];
                    "application/*+json": components["schemas"]["CreateOrganizationRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["OrganizationResponse"];
                        "application/json": components["schemas"]["OrganizationResponse"];
                        "text/json": components["schemas"]["OrganizationResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizations/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["OrganizationResponse"];
                        "application/json": components["schemas"]["OrganizationResponse"];
                        "text/json": components["schemas"]["OrganizationResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RoleResponse"][];
                        "application/json": components["schemas"]["RoleResponse"][];
                        "text/json": components["schemas"]["RoleResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roles/{roleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    roleId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateRoleRequest"];
                    "text/json": components["schemas"]["UpdateRoleRequest"];
                    "application/*+json": components["schemas"]["UpdateRoleRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RoleResponse"];
                        "application/json": components["schemas"]["RoleResponse"];
                        "text/json": components["schemas"]["RoleResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserProfileResponse"];
                        "application/json": components["schemas"]["UserProfileResponse"];
                        "text/json": components["schemas"]["UserProfileResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserListResponse"][];
                        "application/json": components["schemas"]["UserListResponse"][];
                        "text/json": components["schemas"]["UserListResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{userId}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ChangeRoleRequest"];
                    "text/json": components["schemas"]["ChangeRoleRequest"];
                    "application/*+json": components["schemas"]["ChangeRoleRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ChangeRoleResponse"];
                        "application/json": components["schemas"]["ChangeRoleResponse"];
                        "text/json": components["schemas"]["ChangeRoleResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/users/{userId}/venue-scopes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateVenueScopesRequest"];
                    "text/json": components["schemas"]["UpdateVenueScopesRequest"];
                    "application/*+json": components["schemas"]["UpdateVenueScopesRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UpdateVenueScopesResponse"];
                        "application/json": components["schemas"]["UpdateVenueScopesResponse"];
                        "text/json": components["schemas"]["UpdateVenueScopesResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/venues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["VenueResponse"][];
                        "application/json": components["schemas"]["VenueResponse"][];
                        "text/json": components["schemas"]["VenueResponse"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateVenueRequest"];
                    "text/json": components["schemas"]["CreateVenueRequest"];
                    "application/*+json": components["schemas"]["CreateVenueRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["VenueResponse"];
                        "application/json": components["schemas"]["VenueResponse"];
                        "text/json": components["schemas"]["VenueResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/venues/{venueId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    venueId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["VenueResponse"];
                        "application/json": components["schemas"]["VenueResponse"];
                        "text/json": components["schemas"]["VenueResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    venueId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AcceptInvitationRequest: {
            token?: string | null;
            password?: string | null;
        };
        AcceptInvitationResponse: {
            accessToken?: string | null;
            refreshToken?: string | null;
            /** Format: int32 */
            expiresIn?: number;
            /** Format: uuid */
            organizationId?: string;
        };
        AuthResponse: {
            accessToken?: string | null;
            refreshToken?: string | null;
            /** Format: int32 */
            expiresIn?: number;
        };
        BlockTotalsDto: {
            /** Format: double */
            proforma?: number;
            /** Format: double */
            settlement?: number;
            /** Format: double */
            qboActual?: number;
        };
        ChangeRoleRequest: {
            /** Format: uuid */
            roleId?: string;
        };
        ChangeRoleResponse: {
            /** Format: uuid */
            userId?: string;
            /** Format: uuid */
            roleId?: string;
            roleName?: string | null;
        };
        CreateArtistRequest: {
            artistName?: string | null;
            /** Format: int32 */
            performanceOrder?: number;
            dealType?: string | null;
            customFormulaExpression?: string | null;
            /** Format: double */
            baseGuarantee?: number;
            /** Format: double */
            backendPercentage?: number;
            /** Format: double */
            taxWithholdingPercentage?: number;
        };
        CreateEventRequest: {
            title?: string | null;
            eventDate?: string | null;
            qboTagName?: string | null;
        };
        CreateInvitationRequest: {
            email?: string | null;
            /** Format: uuid */
            roleId?: string;
            venueIds?: string[] | null;
        };
        CreateLineItemRequest: {
            blockType?: string | null;
            rowLabel?: string | null;
            /** Format: int32 */
            sortOrder?: number;
            isArtistDeduction?: boolean;
            /** Format: double */
            proformaValue?: number;
            /** Format: double */
            settlementValue?: number;
            notes?: string | null;
            isHiddenFromPromoter?: boolean;
        };
        CreateOrganizationRequest: {
            name?: string | null;
        };
        CreateVenueRequest: {
            name?: string | null;
        };
        EditabilityDto: {
            proforma?: string | null;
            settlement?: string | null;
            qboActuals?: string | null;
        };
        EventArtistDto: {
            /** Format: uuid */
            id?: string;
            artistName?: string | null;
            /** Format: int32 */
            performanceOrder?: number;
            dealType?: string | null;
            customFormulaExpression?: string | null;
            /** Format: double */
            baseGuarantee?: number;
            /** Format: double */
            backendPercentage?: number;
            /** Format: double */
            taxWithholdingPercentage?: number;
            /** Format: double */
            calculatedNetPayout?: number;
            rowVersion?: string | null;
        };
        EventResponse: {
            /** Format: uuid */
            eventId?: string;
            /** Format: uuid */
            venueId?: string;
            title?: string | null;
            eventDate?: string | null;
            status?: string | null;
            isBudgetLocked?: boolean;
            qboTagName?: string | null;
            editability?: components["schemas"]["EditabilityDto"];
        };
        InvitationResponse: {
            /** Format: uuid */
            id?: string;
            email?: string | null;
            roleName?: string | null;
            status?: string | null;
            /** Format: date-time */
            expiresAt?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        LedgerBlockDto: {
            blockType?: string | null;
            rows?: components["schemas"]["LineItemDto"][] | null;
            blockTotals?: components["schemas"]["BlockTotalsDto"];
        };
        LedgerGridResponse: {
            /** Format: uuid */
            eventId?: string;
            /** Format: uuid */
            venueId?: string;
            title?: string | null;
            eventDate?: string | null;
            status?: string | null;
            isBudgetLocked?: boolean;
            qboTagName?: string | null;
            editability?: components["schemas"]["EditabilityDto"];
            blocks?: components["schemas"]["LedgerBlockDto"][] | null;
            artists?: components["schemas"]["EventArtistDto"][] | null;
            summary?: components["schemas"]["LedgerSummaryDto"];
        };
        LedgerSummaryDto: {
            /** Format: double */
            grossRevenue?: number;
            /** Format: double */
            totalDeductions?: number;
            /** Format: double */
            netShowRevenue?: number;
        };
        LineItemDto: {
            /** Format: uuid */
            id?: string;
            rowLabel?: string | null;
            /** Format: int32 */
            sortOrder?: number;
            isArtistDeduction?: boolean;
            /** Format: double */
            proformaValue?: number;
            /** Format: double */
            settlementValue?: number;
            /** Format: double */
            qboActualValue?: number;
            /** Format: double */
            variance?: number;
            varianceFlagged?: boolean;
            notes?: string | null;
            isHiddenFromPromoter?: boolean;
            rowVersion?: string | null;
        };
        LoginRequest: {
            email?: string | null;
            password?: string | null;
        };
        OrganizationResponse: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            /** Format: date-time */
            createdAt?: string;
        };
        OrganizationSummaryDto: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
        };
        PermissionsDto: {
            canManagePermissions?: boolean;
            canLockBudget?: boolean;
            canEditSettlement?: boolean;
            canSignSettlement?: boolean;
            canTriggerQboSync?: boolean;
            canMapQboAccounts?: boolean;
            canViewFinancials?: boolean;
        };
        RefreshRequest: {
            refreshToken?: string | null;
        };
        RegisterRequest: {
            email?: string | null;
            password?: string | null;
        };
        RegisterResponse: {
            /** Format: uuid */
            id?: string;
            email?: string | null;
            /** Format: date-time */
            createdAt?: string;
        };
        RoleDetailDto: {
            /** Format: uuid */
            id?: string;
            roleName?: string | null;
            permissions?: components["schemas"]["PermissionsDto"];
        };
        RoleResponse: {
            /** Format: uuid */
            id?: string;
            roleName?: string | null;
            canManagePermissions?: boolean;
            canLockBudget?: boolean;
            canEditSettlement?: boolean;
            canSignSettlement?: boolean;
            canTriggerQboSync?: boolean;
            canMapQboAccounts?: boolean;
            canViewFinancials?: boolean;
        };
        RoleSummaryDto: {
            /** Format: uuid */
            id?: string;
            roleName?: string | null;
        };
        UpdateArtistRequest: {
            artistName?: string | null;
            /** Format: int32 */
            performanceOrder?: number;
            dealType?: string | null;
            customFormulaExpression?: string | null;
            /** Format: double */
            baseGuarantee?: number;
            /** Format: double */
            backendPercentage?: number;
            /** Format: double */
            taxWithholdingPercentage?: number;
            rowVersion?: string | null;
        };
        UpdateLineItemRequest: {
            rowLabel?: string | null;
            /** Format: int32 */
            sortOrder?: number;
            isArtistDeduction?: boolean;
            /** Format: double */
            proformaValue?: number;
            /** Format: double */
            settlementValue?: number;
            notes?: string | null;
            isHiddenFromPromoter?: boolean;
            rowVersion?: string | null;
        };
        UpdateRoleRequest: {
            canManagePermissions?: boolean | null;
            canLockBudget?: boolean | null;
            canEditSettlement?: boolean | null;
            canSignSettlement?: boolean | null;
            canTriggerQboSync?: boolean | null;
            canMapQboAccounts?: boolean | null;
            canViewFinancials?: boolean | null;
        };
        UpdateVenueScopesRequest: {
            venueIds?: string[] | null;
        };
        UpdateVenueScopesResponse: {
            /** Format: uuid */
            userId?: string;
            venueScopes?: components["schemas"]["VenueScopeDto"][] | null;
        };
        UserListResponse: {
            /** Format: uuid */
            id?: string;
            email?: string | null;
            role?: components["schemas"]["RoleSummaryDto"];
            venueScopes?: components["schemas"]["VenueScopeDto"][] | null;
        };
        UserProfileResponse: {
            /** Format: uuid */
            id?: string;
            email?: string | null;
            organization?: components["schemas"]["OrganizationSummaryDto"];
            role?: components["schemas"]["RoleDetailDto"];
            venueScopes?: components["schemas"]["VenueScopeDto"][] | null;
        };
        VenueResponse: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            /** Format: uuid */
            organizationId?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        VenueScopeDto: {
            /** Format: uuid */
            venueId?: string;
            venueName?: string | null;
        };
        SyncResultDto: {
            /** Format: uuid */
            eventId?: string;
            /** Format: uuid */
            syncBatchId?: string;
            transactionsProcessed?: number;
            transactionsMapped?: number;
            transactionsUnmapped?: number;
            unmappedAccountIds?: string[] | null;
            /** Format: date-time */
            syncedAt?: string;
        };
        SyncStatusDto: {
            /** Format: uuid */
            eventId?: string;
            /** Format: date-time */
            lastSyncedAt?: string | null;
            /** Format: uuid */
            lastSyncBatchId?: string | null;
            totalMappedTransactions?: number;
            totalUnmappedTransactions?: number;
            qboConnected?: boolean;
        };
        QboAccountMappingDto: {
            /** Format: uuid */
            id?: string;
            qboAccountId?: string | null;
            qboAccountName?: string | null;
            mappedCategoryLabel?: string | null;
            /** Format: uuid */
            mappedLineItemId?: string | null;
            /** Format: date-time */
            createdAt?: string;
        };
        QboAccountMappingsResponse: {
            /** Format: uuid */
            venueId?: string;
            mappings?: components["schemas"]["QboAccountMappingDto"][] | null;
        };
        CreateMappingRequest: {
            qboAccountId?: string | null;
            qboAccountName?: string | null;
            mappedCategoryLabel?: string | null;
            /** Format: uuid */
            mappedLineItemId?: string | null;
        };
        UpdateMappingRequest: {
            mappedCategoryLabel?: string | null;
            /** Format: uuid */
            mappedLineItemId?: string | null;
        };
        UnmappedTransactionDto: {
            /** Format: uuid */
            id?: string;
            qboTransactionId?: string | null;
            qboAccountId?: string | null;
            qboAccountName?: string | null;
            amount?: string | null;
            transactionDate?: string | null;
            /** Format: date-time */
            syncedAt?: string;
        };
        UnmappedTransactionsResponse: {
            /** Format: uuid */
            eventId?: string;
            /** Format: uuid */
            venueId?: string;
            unmappedCount?: number;
            transactions?: components["schemas"]["UnmappedTransactionDto"][] | null;
        };
        UnmappedCountDto: {
            /** Format: uuid */
            eventId?: string;
            unmappedCount?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;

export type SyncResultDto = components['schemas']['SyncResultDto'];
export type SyncStatusDto = components['schemas']['SyncStatusDto'];
export type QboAccountMappingDto = components['schemas']['QboAccountMappingDto'];
export type QboAccountMappingsResponse = components['schemas']['QboAccountMappingsResponse'];
export type CreateMappingRequest = components['schemas']['CreateMappingRequest'];
export type UpdateMappingRequest = components['schemas']['UpdateMappingRequest'];
export type UnmappedTransactionDto = components['schemas']['UnmappedTransactionDto'];
export type UnmappedTransactionsResponse = components['schemas']['UnmappedTransactionsResponse'];
export type UnmappedCountDto = components['schemas']['UnmappedCountDto'];
export type UserProfileResponse = components['schemas']['UserProfileResponse'];
