// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SplitRail.Api.Data;

#nullable disable

namespace SplitRail.Api.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260626233046_AddQboCoreIntegrationEntities")]
    partial class AddQboCoreIntegrationEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SplitRail.Api.Models.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ArtistSignatureData")
                        .HasColumnType("text")
                        .HasColumnName("artist_signature_data");

                    b.Property<string>("BookingPlacementStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("CONFIRMED")
                        .HasColumnName("booking_placement_status");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<TimeOnly?>("CurfewTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("curfew_time");

                    b.Property<TimeOnly?>("DoorsTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("doors_time");

                    b.Property<DateOnly>("EventDate")
                        .HasColumnType("date")
                        .HasColumnName("event_date");

                    b.Property<bool>("IsBudgetLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_budget_locked");

                    b.Property<TimeOnly?>("LoadInTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("load_in_time");

                    b.Property<string>("QboTagName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("qbo_tag_name");

                    b.Property<DateTimeOffset?>("ReconciledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reconciled_at");

                    b.Property<Guid?>("ReconciledByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reconciled_by_user_id");

                    b.Property<DateTimeOffset?>("SettledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("settled_at");

                    b.Property<Guid?>("SettledByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("settled_by_user_id");

                    b.Property<string>("SettlementPdfUrl")
                        .HasColumnType("text")
                        .HasColumnName("settlement_pdf_url");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("PRE_SHOW")
                        .HasColumnName("status");

                    b.Property<string>("SupportLineup")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("support_lineup");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid")
                        .HasColumnName("venue_id");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ReconciledByUserId");

                    b.HasIndex("SettledByUserId");

                    b.HasIndex("VenueId")
                        .HasDatabaseName("IX_events_venue_id");

                    b.HasIndex("VenueId", "EventDate")
                        .HasDatabaseName("ix_events_venue_id_event_date");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("SplitRail.Api.Models.EventArtist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ArtistName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("artist_name");

                    b.Property<decimal>("BackendPercentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("backend_percentage");

                    b.Property<decimal>("BaseGuarantee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("base_guarantee");

                    b.Property<decimal>("CalculatedNetPayout")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("calculated_net_payout");

                    b.Property<string>("CustomFormulaExpression")
                        .HasColumnType("text")
                        .HasColumnName("custom_formula_expression");

                    b.Property<string>("DealType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("deal_type");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<int>("PerformanceOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("performance_order");

                    b.Property<decimal>("TaxWithholdingPercentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("tax_withholding_percentage");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .HasDatabaseName("IX_event_artists_event_id");

                    b.ToTable("event_artists", (string)null);
                });

            modelBuilder.Entity("SplitRail.Api.Models.FinancialLineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("BlockType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("block_type");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<bool>("IsArtistDeduction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_artist_deduction");

                    b.Property<bool>("IsHiddenFromPromoter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_hidden_from_promoter");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<decimal>("ProformaValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("proforma_value");

                    b.Property<decimal>("QboActualValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("qbo_actual_value");

                    b.Property<string>("RowLabel")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("row_label");

                    b.Property<decimal>("SettlementValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("settlement_value");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .HasDatabaseName("IX_financial_line_items_event_id");

                    b.HasIndex("EventId", "BlockType", "SortOrder")
                        .HasDatabaseName("IX_financial_line_items_event_block_sort");

                    b.ToTable("financial_line_items", (string)null);
                });

            modelBuilder.Entity("SplitRail.Api.Models.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("IX_invitations_organization_id");

                    b.HasIndex("RoleId");

                    b.HasIndex("TokenHash")
                        .HasDatabaseName("IX_invitations_token_hash");

                    b.ToTable("invitations", (string)null);
                });

            modelBuilder.Entity("SplitRail.Api.Models.InvitationVenueScope", b =>
                {
                    b.Property<Guid>("InvitationId")
                        .HasColumnType("uuid")
                        .HasColumnName("invitation_id");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid")
                        .HasColumnName("venue_id");

                    b.HasKey("InvitationId", "VenueId");

                    b.HasIndex("VenueId");

                    b.ToTable("invitation_venue_scopes", (string)null);
                });

            modelBuilder.Entity("SplitRail.Api.Models.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("America/Denver")
                        .HasColumnName("time_zone_id");

                    b.HasKey("Id");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("SplitRail.Api.Models.OrganizationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("CanEditSettlement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("can_edit_settlement");

                    b.Property<bool>("CanLockBudget")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("can_lock_budget");

                    b.Property<bool>("CanManagePermissions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("can_manage_permissions");

                    b.Property<bool>("CanMapQboAccounts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("can_map_qbo_accounts");

                    b.Property<bool>("CanReverseSettlement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("can_reverse_settlement");

                    b.Property<bool>("CanSignSettlement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("can_sign_settlement");

                    b.Property<bool>("CanTriggerQboSync")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("can_trigger_qbo_sync");

                    b.Property<bool>("CanViewFinancials")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("can_view_financials");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("role_name");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "RoleName")
                        .IsUnique()
                        .HasDatabaseName("unique_role_per_org");

                    b.ToTable("organization_roles", (string)null);
                });

            modelBuilder.Entity("SplitRail.Api.Models.QboAccountMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("MappedCategoryLabel")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("mapped_category_label");

                    b.Property<Guid?>("MappedLineItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("mapped_line_item_id");

                    b.Property<string>("QboAccountId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("qbo_account_id");

                    b.Property<string>("QboAccountName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("qbo_account_name");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid")
                        .HasColumnName("venue_id");

                    b.HasKey("Id");

                    b.HasIndex("MappedLineItemId");

                    b.HasIndex("VenueId", "QboAccountId")
                        .IsUnique()
                        .HasDatabaseName("IX_qbo_account_mappings_venue_account");

                    b.ToTable("qbo_account_mappings", (string)null);
                });

            modelBuilder.Entity("SplitRail.Api.Models.QboSyncLedger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<Guid?>("CorrectedLedgerEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("corrected_ledger_entry_id");

                    b.Property<string>("CorrectionType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("correction_type");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Original")
                        .HasColumnName("entry_type");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<Guid?>("MappedLineItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("mapped_line_item_id");

                    b.Property<string>("QboAccountId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("qbo_account_id");

                    b.Property<string>("QboTransactionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("qbo_transaction_id");

                    b.Property<Guid>("SyncBatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_batch_id");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool?>("TargetStateAbsent")
                        .HasColumnType("boolean")
                        .HasColumnName("target_state_absent");

                    b.Property<decimal?>("TargetStateAmount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("target_state_amount");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("date")
                        .HasColumnName("transaction_date");

                    b.HasKey("Id");

                    b.HasIndex("CorrectedLedgerEntryId");

                    b.HasIndex("MappedLineItemId")
                        .HasDatabaseName("IX_qbo_sync_ledger_mapped_line_item_id");

                    b.HasIndex("EventId", "EntryType")
                        .HasDatabaseName("IX_qbo_sync_ledger_event_entry_type");

                    b.HasIndex("EventId", "QboTransactionId")
                        .IsUnique()
                        .HasDatabaseName("IX_qbo_sync_ledger_event_txn_original")
                        .HasFilter("entry_type = 'Original'");

                    b.HasIndex("EventId", "QboTransactionId", "CorrectionType", "TargetStateAbsent", "TargetStateAmount")
                        .IsUnique()
                        .HasDatabaseName("IX_qbo_sync_ledger_offset_idempotency")
                        .HasFilter("entry_type = 'OffsetCorrection'");

                    b.ToTable("qbo_sync_ledger", (string)null);
                });

            modelBuilder.Entity("SplitRail.Api.Models.QboTrackingMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("QboTrackingId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("qbo_tracking_id");

                    b.Property<string>("QboTrackingName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("qbo_tracking_name");

                    b.Property<string>("QboTrackingType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("qbo_tracking_type");

                    b.Property<Guid>("TargetEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_entity_id");

                    b.Property<string>("TargetTier")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("target_tier");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid")
                        .HasColumnName("venue_id");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("VenueId", "QboTrackingId", "TargetTier", "TargetEntityId")
                        .IsUnique()
                        .HasDatabaseName("IX_qbo_tracking_mappings_venue_tracking_target");

                    b.ToTable("qbo_tracking_mappings", (string)null);
                });

            modelBuilder.Entity("SplitRail.Api.Models.QboVenueCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("company_name");

                    b.Property<DateTimeOffset>("ConnectedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("connected_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid?>("ConnectedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("connected_by_user_id");

                    b.Property<string>("EncryptedAccessToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("encrypted_access_token");

                    b.Property<string>("EncryptedRefreshToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("encrypted_refresh_token");

                    b.Property<bool>("IsExpired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_expired");

                    b.Property<string>("RealmId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("realm_id");

                    b.Property<DateTimeOffset>("TokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("token_expires_at");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid")
                        .HasColumnName("venue_id");

                    b.HasKey("Id");

                    b.HasIndex("ConnectedByUserId");

                    b.HasIndex("VenueId")
                        .IsUnique()
                        .HasDatabaseName("IX_qbo_venue_credentials_venue_id");

                    b.ToTable("qbo_venue_credentials", (string)null);
                });

            modelBuilder.Entity("SplitRail.Api.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .HasDatabaseName("IX_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("SplitRail.Api.Models.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_regions_organization_id_name");

                    b.ToTable("regions", (string)null);
                });

            modelBuilder.Entity("SplitRail.Api.Models.SettlementReversal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("PreviousPdfUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("previous_pdf_url");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("ReversedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reversed_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid?>("ReversedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reversed_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .HasDatabaseName("IX_settlement_reversals_event_id");

                    b.HasIndex("ReversedByUserId");

                    b.ToTable("settlement_reversals", (string)null);
                });

            modelBuilder.Entity("SplitRail.Api.Models.UnmappedQboTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("QboAccountId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("qbo_account_id");

                    b.Property<string>("QboAccountName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("qbo_account_name");

                    b.Property<string>("QboTransactionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("qbo_transaction_id");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("date")
                        .HasColumnName("transaction_date");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid")
                        .HasColumnName("venue_id");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "QboTransactionId")
                        .IsUnique()
                        .HasDatabaseName("IX_unmapped_qbo_txn_event_txn");

                    b.HasIndex("VenueId", "QboAccountId")
                        .HasDatabaseName("IX_unmapped_qbo_txn_venue_account");

                    b.ToTable("unmapped_qbo_transactions", (string)null);
                });

            modelBuilder.Entity("SplitRail.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SplitRail.Api.Models.UserEventPin", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset>("PinnedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pinned_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("UserId", "EventId");

                    b.HasIndex("EventId");

                    b.ToTable("user_event_pins", (string)null);
                });

            modelBuilder.Entity("SplitRail.Api.Models.UserOrganizationMapping", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "OrganizationId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_organization_mappings", (string)null);
                });

            modelBuilder.Entity("SplitRail.Api.Models.UserVenueScope", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid")
                        .HasColumnName("venue_id");

                    b.HasKey("UserId", "VenueId");

                    b.HasIndex("VenueId");

                    b.ToTable("user_venue_scopes", (string)null);
                });

            modelBuilder.Entity("SplitRail.Api.Models.Venue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid?>("RegionId")
                        .HasColumnType("uuid")
                        .HasColumnName("region_id");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("RegionId")
                        .HasDatabaseName("ix_venues_region_id");

                    b.ToTable("venues", (string)null);
                });

            modelBuilder.Entity("SplitRail.Api.Models.Event", b =>
                {
                    b.HasOne("SplitRail.Api.Models.User", "ReconciledByUser")
                        .WithMany()
                        .HasForeignKey("ReconciledByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SplitRail.Api.Models.User", "SettledByUser")
                        .WithMany()
                        .HasForeignKey("SettledByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SplitRail.Api.Models.Venue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReconciledByUser");

                    b.Navigation("SettledByUser");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("SplitRail.Api.Models.EventArtist", b =>
                {
                    b.HasOne("SplitRail.Api.Models.Event", "Event")
                        .WithMany("Artists")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("SplitRail.Api.Models.FinancialLineItem", b =>
                {
                    b.HasOne("SplitRail.Api.Models.Event", "Event")
                        .WithMany("LineItems")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("SplitRail.Api.Models.Invitation", b =>
                {
                    b.HasOne("SplitRail.Api.Models.Organization", "Organization")
                        .WithMany("Invitations")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SplitRail.Api.Models.OrganizationRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SplitRail.Api.Models.InvitationVenueScope", b =>
                {
                    b.HasOne("SplitRail.Api.Models.Invitation", "Invitation")
                        .WithMany("VenueScopes")
                        .HasForeignKey("InvitationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SplitRail.Api.Models.Venue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invitation");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("SplitRail.Api.Models.OrganizationRole", b =>
                {
                    b.HasOne("SplitRail.Api.Models.Organization", "Organization")
                        .WithMany("Roles")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("SplitRail.Api.Models.QboAccountMapping", b =>
                {
                    b.HasOne("SplitRail.Api.Models.FinancialLineItem", "MappedLineItem")
                        .WithMany()
                        .HasForeignKey("MappedLineItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SplitRail.Api.Models.Venue", "Venue")
                        .WithMany("QboAccountMappings")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MappedLineItem");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("SplitRail.Api.Models.QboSyncLedger", b =>
                {
                    b.HasOne("SplitRail.Api.Models.QboSyncLedger", "CorrectedLedgerEntry")
                        .WithMany()
                        .HasForeignKey("CorrectedLedgerEntryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SplitRail.Api.Models.Event", "Event")
                        .WithMany("QboSyncLedgerEntries")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SplitRail.Api.Models.FinancialLineItem", "MappedLineItem")
                        .WithMany()
                        .HasForeignKey("MappedLineItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CorrectedLedgerEntry");

                    b.Navigation("Event");

                    b.Navigation("MappedLineItem");
                });

            modelBuilder.Entity("SplitRail.Api.Models.QboTrackingMapping", b =>
                {
                    b.HasOne("SplitRail.Api.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SplitRail.Api.Models.Venue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("SplitRail.Api.Models.QboVenueCredential", b =>
                {
                    b.HasOne("SplitRail.Api.Models.User", "ConnectedByUser")
                        .WithMany()
                        .HasForeignKey("ConnectedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SplitRail.Api.Models.Venue", "Venue")
                        .WithOne("QboCredential")
                        .HasForeignKey("SplitRail.Api.Models.QboVenueCredential", "VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConnectedByUser");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("SplitRail.Api.Models.RefreshToken", b =>
                {
                    b.HasOne("SplitRail.Api.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SplitRail.Api.Models.Region", b =>
                {
                    b.HasOne("SplitRail.Api.Models.Organization", "Organization")
                        .WithMany("Regions")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("SplitRail.Api.Models.SettlementReversal", b =>
                {
                    b.HasOne("SplitRail.Api.Models.Event", "Event")
                        .WithMany("Reversals")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SplitRail.Api.Models.User", "ReversedByUser")
                        .WithMany()
                        .HasForeignKey("ReversedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Event");

                    b.Navigation("ReversedByUser");
                });

            modelBuilder.Entity("SplitRail.Api.Models.UnmappedQboTransaction", b =>
                {
                    b.HasOne("SplitRail.Api.Models.Event", "Event")
                        .WithMany("UnmappedQboTransactions")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SplitRail.Api.Models.Venue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("SplitRail.Api.Models.UserEventPin", b =>
                {
                    b.HasOne("SplitRail.Api.Models.Event", "Event")
                        .WithMany("UserEventPins")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SplitRail.Api.Models.User", "User")
                        .WithMany("EventPins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SplitRail.Api.Models.UserOrganizationMapping", b =>
                {
                    b.HasOne("SplitRail.Api.Models.Organization", "Organization")
                        .WithMany("UserMappings")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SplitRail.Api.Models.OrganizationRole", "Role")
                        .WithMany("UserMappings")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SplitRail.Api.Models.User", "User")
                        .WithMany("OrganizationMappings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SplitRail.Api.Models.UserVenueScope", b =>
                {
                    b.HasOne("SplitRail.Api.Models.User", "User")
                        .WithMany("VenueScopes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SplitRail.Api.Models.Venue", "Venue")
                        .WithMany("UserVenueScopes")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("SplitRail.Api.Models.Venue", b =>
                {
                    b.HasOne("SplitRail.Api.Models.Organization", "Organization")
                        .WithMany("Venues")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SplitRail.Api.Models.Region", "Region")
                        .WithMany("Venues")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Organization");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("SplitRail.Api.Models.Event", b =>
                {
                    b.Navigation("Artists");

                    b.Navigation("LineItems");

                    b.Navigation("QboSyncLedgerEntries");

                    b.Navigation("Reversals");

                    b.Navigation("UnmappedQboTransactions");

                    b.Navigation("UserEventPins");
                });

            modelBuilder.Entity("SplitRail.Api.Models.Invitation", b =>
                {
                    b.Navigation("VenueScopes");
                });

            modelBuilder.Entity("SplitRail.Api.Models.Organization", b =>
                {
                    b.Navigation("Invitations");

                    b.Navigation("Regions");

                    b.Navigation("Roles");

                    b.Navigation("UserMappings");

                    b.Navigation("Venues");
                });

            modelBuilder.Entity("SplitRail.Api.Models.OrganizationRole", b =>
                {
                    b.Navigation("UserMappings");
                });

            modelBuilder.Entity("SplitRail.Api.Models.Region", b =>
                {
                    b.Navigation("Venues");
                });

            modelBuilder.Entity("SplitRail.Api.Models.User", b =>
                {
                    b.Navigation("EventPins");

                    b.Navigation("OrganizationMappings");

                    b.Navigation("RefreshTokens");

                    b.Navigation("VenueScopes");
                });

            modelBuilder.Entity("SplitRail.Api.Models.Venue", b =>
                {
                    b.Navigation("QboAccountMappings");

                    b.Navigation("QboCredential");

                    b.Navigation("UserVenueScopes");
                });
#pragma warning restore 612, 618
        }
    }
}
